### ISSUE TITLE
npm usage

### ISSUE THREAD

**Issue by lmangani** [tmpfs-archive/husk#4]
Fantastic design! Trying to get familiar and understand the usage pattern - what is this intended format to load up internal plugins when using the npm `husk` module and/or externally distributed modules?
```
var husk = require('husk')
  .plugin([
    require('husk-transform')
  ]);
```
`Cannot find module 'husk-transform'`

Thanks in advance!

**Comment by tmpfs** [comment]
Thanks for the kind words, this was really just an experiment for me to learn nodejs streams thoroughly.

The module you refer to exists in the registry and your syntax is correct. Have you added the module:

```
npm i --save husk-transform
```

Ta.
